### ISSUE TITLE
Support for the new ADISU Campania website

### ISSUE THREAD

**Issue by qub1750ul** [Zekromaster/MensaUnisa-Cacher#1]
ADISU Campania recently [rebuilt their site](https://adisurcampania.it/notizie/avvio-nuovo-sito-web), completely changing directory structure. Old resource links won't work anymore.

**Comment by qub1750ul** [comment]
New menu files can be scraped from:  
https://adisurcampania.it/ristorazione/mense-ed-esercizi-convenzionati/mensa-di-fisciano-e-baronissi#toc-il-men-

**Comment by Zekromaster** [comment]
Interestingly, the menu is now explicitly split by type, which should allow for better distinction of various categories of menu. I'll check it out later.

**Comment by Zekromaster** [comment]
Development of this project was completely stopped.
